getmybook/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import myapp

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('myapp.urls')),
]

myapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from myapp import views
from django.conf import settings
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/home/')),
    url(r'^home/',views.home_view, name='home'),
    url(r'^signup/',views.signup_view, name='signup'),
    url(r'^login/',views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^user/', views.user_view, name='user'),
    url(r'^userbooks/', views.userbooks_view, name='userbooks'),
    url(r'^books/', views.BookListView.as_view(), name='books'),
    url(r'^book/(\d+)/', views.book_detail_view, name='book-detail'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances
from datetime import date
from django.contrib.auth.models import User

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    cover = models.ImageField(upload_to='book_cover',blank=True)
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    publisher = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return '{0}({1})'.format(self.book.title,self.id)


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
    
    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0} {1}'.format(self.first_name,self.last_name)

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    first_name = forms.CharField(max_length=20, help_text='Required. Inform a valid email address.')
    last_name = forms.CharField(max_length=20, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ( 'first_name', 'last_name', 'email', 'username', 'password1', 'password2', )

myapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate,logout
from .forms import SignUpForm
from django.contrib.auth.models import User
from myapp.models import Book, Author, BookInstance, Genre
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin




class BookListView(ListView):
    model = Book
    context_object_name = 'book_list'   # your own name for the list as a template variable
    queryset = Book.objects.all() # Get 5 books
    template_name = 'myapp/books.html' 
    paginate_by = 30


def book_detail_view(request, primary_key):
    book = get_object_or_404(Book, pk=primary_key)
    return render(request, 'myapp/book_detail.html', context={'book': book})

def home_view(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    
    # The 'all()' is implied by default.    
    num_authors = Author.objects.count()
    
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'myapp/homepage.html', context=context)

def user_view(request):
    if request.user.is_authenticated:
        return render(request,'myapp/userpage.html')
    else:
        error = 'Login to continue'
    return render(request,'myapp/loginpage.html',{'error':error})


def userbooks_view(request):
    if request.user.is_authenticated:
        bookinstance_list = BookInstance.objects.filter(borrower=request.user).filter(status__exact='o').order_by('due_back')
        return render(request,'myapp/userbooks.html',{'bookinstance_list':bookinstance_list})
    


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(user_view)
    else:
        form = SignUpForm()
    return render(request,'myapp/signuppage.html',{'form':form})

def login_view(request):
    error = ''
    if request.user.is_authenticated:
            return redirect(user_view)
    if request.method =='POST':
        username = request.POST["username"]
        raw_password = request.POST["password"]
        if User.objects.filter(username=username).exists():
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(user_view)
        else:
            error = 'Username or password Incorrect'
    return render(request,'myapp/loginpage.html',{'error':error})

def logout_view(request):
    logout(request)
    return render(request,'myapp/loginpage.html',{})

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Title | here{% endblock %}</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

      {% block style %}
      {% endblock %}

      {% block script %}
      {% endblock %}

</head>


<body>

  <nav class="navbar navbar-expand-md bg-light navbar-light" style="box-shadow: 0px 10px 39px 5px rgba(0,0,0,0.57);">
    {% load static %}
    <a class="navbar-brand" href="/home/"><img src="{% static 'logo.png' %}" alt="logo" width="180px" height="50px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="/home/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/books/">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>   
      </ul>                
    </div> 
    <div class="collapse navbar-collapse justify-content-end" id="nav-content">   
      <ul class="navbar-nav">

        {% block login %}
        {% endblock %}

      </ul> 
    </div>
  </nav>

  {% block content %}
  content goes here
  {% endblock %}

  {% block pagination %}
    {% if is_paginated %}
      <div class="pagination">
        <span class="page-links">
          {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
          <span class="page-current">
            <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
          </span>
          {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
          {% endif %}
        </span>
      </div>
    {% endif %}
  {% endblock %}
  
</body>

</html>

myapp/templates/myapp/book_detail.html
{% extends "myapp/base.html" %}
{% block title %}{{ book.title }} | Get My Book{% endblock %}

{% block login %}
{% if user.is_authenticated %}
<li class="nav-item">
    <a class="nav-link" href="#"><i class="fa fa-user-circle"></i> {{request.user.first_name}}</a>
</li> 
<li class="nav-item">
    <a class="nav-link" href="/logout/"><i class="fa fa-sign-out"></i> Logout</a>
</li>  
{% else %}
<li class="nav-item">
    <a class="nav-link" href="/signup/"><i class="fa fa-user-plus"></i> Sign Up</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="/login/"><i class="fa fa-sign-in"></i> Login</a>
</li>
{% endif %}
{% endblock %}  

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      <p><strong>Published:</strong> {{copy.publisher}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

myapp/templates/myapp/books.html
{% block style %}
<style>
    .card :hover {background: rgba(0, 0, 0, .8);}

</style>
{% endblock %}

{% block content %}
  
  <div class="container">
     <h1 class="card" style="margin-top: 2%;background: rgba(0, 0, 0, .8);color: white;" >Book List</h1>
  {% if book_list %}
  <div class="card-deck">
    {% for book in book_list %}
        <a href="{{ book.get_absolute_url }}">
                <div class="card"style=" width: 150px !important ; -webkit-box-shadow: 0px 0px 43px 6px rgba(0,0,0,0.75);
                -moz-box-shadow: 0px 0px 43px 6px rgba(0,0,0,0.75);
                box-shadow: 0px 0px 43px 6px rgba(0,0,0,0.75);" >
                <img class="card-img-top" src="{{book.cover.url}}" alt="Card image cap" style="height:200px !important; width:150px !important;">
                <div class="card-img-overlay card_header">
                    <h5 class="card-title" style="color: white;"> <b>{{ book.title }}</b> </h5>
                    <p class="card-text" style="color: white;"><i>({{book.author}})</i>  </p>
                </div>
            </div> 
        </a>
        
    {% endfor %}  
  </div> 
  </div>
  
    
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}  
  
  
  
{% endblock %}

myapp/templates/myapp/homepage.html
{% extends 'myapp/base.html' %}
{% block title %}Home | Get My Book{% endblock %}

{% block style %}
<style>
    
    .list-group-item{
        padding: 2%;
    }
    .card-title{
        padding-bottom: 0%;
    }

    

    .jumbotron {
        margin-bottom: 0px;
        height: 250px;
        color: white;
        text-shadow: black 0.3em 0.3em 0.3em;
        background: url('https://images.pexels.com/photos/34592/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940') no-repeat center center ;
    }
    
    .jumbotron img{
        background: rgba(0,0,0,0.75);
        width: 300px;
    }
</style>
{% endblock %}

{% block script %}
    <script> 
    $(function(){
      $("#includedContent").load("/books/"); 
    });
    </script> 

{% endblock %}


{% block login %}
{% if user.is_authenticated %}
<li class="nav-item">
    <a class="nav-link" href="/userbooks/" ><i class="fa fa-user-circle"></i> {{request.user.first_name}}</a>
</li> 
<li class="nav-item">
    <a class="nav-link" href="/logout/"><i class="fa fa-sign-out"></i> Logout</a>
</li>  
{% else %}
<li class="nav-item">
    <a class="nav-link" href="/signup/"><i class="fa fa-user-plus"></i> Sign Up</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="/login/"><i class="fa fa-sign-in"></i> Login</a>
</li>
{% endif %}
{% endblock %} 


{% block content %}
{% load static %}
<div class="jumbotron text-center " >
    <img src="{% static 'logo.png' %}"  alt="logo">
    <p>Welcome, a Library Management System developed by <em>Eashwer K S</em>!</p>
</div>
<div class="container">
        <div class="row">
          <div id="includedContent" class="col-sm-8">
            
          </div>
          <div class="col-sm-4">
            <div class="card ">
                <h5 class="card-title" style="color:#E36262;">Dynamic content</h5>
                <p class="card-text">The library has the following record counts:</p>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><strong>Books:</strong> {{ num_books }}</li>
                    <li class="list-group-item"><strong>Copies:</strong> {{ num_instances }}</li>
                    <li class="list-group-item"><strong>Copies available:</strong> {{ num_instances_available }}</li>
                    <li class="list-group-item"><strong>Authors:</strong> {{ num_authors }}</li>
                </ul>
            </div>
          </div>
        </div>

         
    

{% endblock %}

myapp/templates/myapp/loginpage.html
{% extends 'myapp/base.html' %}
{% block title %}Login | Get My Book{% endblock %}
{% block login %}
<li class="nav-item">
    <a class="nav-link" href="/signup/"><i class="fa fa-user-plus"></i> Sign Up</a>
</li>
{% endblock %}




{% block style %}
<style>
    @import url("//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css");
    .login-block{
    background: #DE6262;  /* fallback for old browsers */
    background: -webkit-linear-gradient(to bottom, #FFB88C, #DE6262);  /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to bottom, #FFB88C, #DE6262); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    float:left;
    height: 91.7vh;
    width:100%;
    padding : 50px 0;
    margin: 0%;
}
.banner-sec{background:url(https://static.pexels.com/photos/33972/pexels-photo.jpg)  no-repeat left bottom; background-size:cover; min-height:500px; border-radius: 0 10px 10px 0; padding:0;}
.container{background:#fff; border-radius: 10px; box-shadow:15px 20px 0px rgba(0,0,0,0.1);}
.carousel-inner{border-radius:0 10px 10px 0;}
.carousel-caption{text-align:left; left:5%;}
.login-sec{padding: 50px 30px; position:relative;}
.login-sec .copy-text{position:absolute; width:80%; bottom:20px; font-size:13px; text-align:center;}
.login-sec .copy-text i{color:#FEB58A;}
.login-sec .copy-text a{color:#E36262;}
.login-sec h2{margin-bottom:30px; font-weight:800; font-size:30px; color: #DE6262;}
.login-sec h2:after{content:" "; width:100px; height:5px; background:#FEB58A; display:block; margin-top:20px; border-radius:3px; margin-left:auto;margin-right:auto}
.btn-login{background: #DE6262; color:#fff; font-weight:600;}
.banner-text{width:70%; position:absolute; bottom:40px; padding-left:20px;}
.banner-text h2{color:#fff; font-weight:600;}
.banner-text h2:after{content:" "; width:100px; height:5px; background:#FFF; display:block; margin-top:20px; border-radius:3px;}
.banner-text p{color:#fff;}
.error{color: red;}
</style>

{% endblock %}

{% block content %}
<section class="login-block">
    <div class="container">
	<div class="row">
		<div class="col-md-4 login-sec">
		    <h2 class="text-center">Login Now</h2>
        <form method="POST" action="/login/" class="login-form">
          {% csrf_token %}
    <p class="error">{{error}}</p>

  <div class="form-group">
    <label for="exampleInputEmail1" class="text-uppercase">Username</label>
    <input type="text" name="username" class="form-control" placeholder="Username">
    
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1" class="text-uppercase">Password</label>
    <input type="password" name="password" class="form-control" placeholder="Password">
  </div>

    <div class="form-check">
    <label class="form-check-label">
      <input type="checkbox" class="form-check-input">
      <small>Remember Me</small>
    </label>
    <button type="submit" class="btn btn-login float-right">Login</button>
  </div>
  
</form>
<div class="copy-text">Created with <i class="fa fa-heart"></i> by <a href="http://eashwerks.tk">EASHWERKS</a></div>
		</div>
		<div class="col-md-8 banner-sec">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                 <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
            <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block img-fluid" src="https://static.pexels.com/photos/33972/pexels-photo.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <div class="banner-text">
            <h2>This is Heaven</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
        </div>	
  </div>
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="https://images.pexels.com/photos/7097/people-coffee-tea-meeting.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <div class="banner-text">
            <h2>This is Heaven</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
        </div>	
    </div>
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="https://images.pexels.com/photos/872957/pexels-photo-872957.jpeg" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <div class="banner-text">
            <h2>This is Heaven</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
        </div>	
    </div>
  </div>
            </div>	   
		    
		</div>
	</div>
</div>
</section>
{% endblock %}

myapp/templates/myapp/signuppage.html
{% extends 'myapp/base.html' %}
{% block title %}Sign Up | Get My Book{% endblock %}

{% block login %}
<li class="nav-item">
    <a class="nav-link" href="/login/"><i class="fa fa-sign-in"></i> Login</a>
</li>

{% endblock %}

{% block style %}
<style>
        .container {
            max-width: 100%;
        }
        .copy-text{
            padding-left: 8%;
            position:absolute;
            width:80%; 
            bottom:1px; 
            font-size:13px; 
            text-align:center;
        }

        .register{
            background: -webkit-linear-gradient(left, #DE6262 , #FFB88C);
            height: 91.7vh;
            margin: 0%;
            padding: 3%;
        }
        .register-left{
            text-align: center;
            color: #fff;
            margin-top: 4%;
        }
        .register-left input{
            border: none;
            border-radius: 1.5rem;
            padding: 2%;
            width: 60%;
            background: #f8f9fa;
            font-weight: bold;
            color: #383d41;
            margin-top: 30%;
            margin-bottom: 3%;
            cursor: pointer;
        }
        .register-right{
            margin-top: 3%;
            background: #f8f9fa;
            border-top-left-radius: 10% 50%;
            border-bottom-left-radius: 10% 50%;
        }
        .register-left img{
            margin-top: 40%;
            margin-bottom: 5%;
            width: 25%;
          }

        .register-right img{
            width: 20%;
            margin-left: 40%;
            padding-top: 5%;
            -webkit-animation: mover 2s infinite  alternate;
            animation: mover 1s infinite  alternate;
        }

        @-webkit-keyframes mover {
            0% { transform: translateY(0); }
            100% { transform: translateY(-20px); }
        }
        @keyframes mover {
            0% { transform: translateY(0); }
            100% { transform: translateY(-20px); }
        }
        .register-left p{
            font-weight: lighter;
            padding: 12%;
            margin-top: -9%;
        }
        .register .register-form{
            padding: 5%;
            margin-top: 15%;
        }
        .btnRegister{
            float: right;
            margin-top: 10%;
            border: none;
            border-radius: 1.5rem;
            padding: 2%;
            background: #DE6262;
            color: #fff;
            font-weight: 600;
            width: 50%;
            cursor: pointer;
        }
        .register .nav-tabs{
            margin-top: 3%;
            border: none;
            background: #DE6262;
            border-radius: 1.5rem;
            width: 28%;
            float: right;
        }
        .register .nav-tabs .nav-link{
            padding: 2%;
            height: 34px;
            font-weight: 600;
            color: #fff;
            border-top-right-radius: 1.5rem;
            border-bottom-right-radius: 1.5rem;
        }
        .register .nav-tabs .nav-link:hover{
            border: none;
        }
        .register .nav-tabs .nav-link.active{
            width: 100px;
            color:#DE6262;
            border: 2px solid #DE6262;
            border-top-left-radius: 1.5rem;
            border-bottom-left-radius: 1.5rem;
        }
        .register-heading{
            text-align: center;
            margin-bottom: -15%;
            color: #495057;
        }
</style>

{% endblock %}

{% block content %}
<div class="container register">
        <div class="row">
            <div class="col-md-3 register-left">
                {% load static %}
                <img src="{% static 'logoimg.png' %}" alt="logo"/>
                <h3>Welcome</h3>
            </div>
            <form method="POST" action="/signup/" class="col-md-9 register-right">
                {% csrf_token %}
                <div class="tab-content" id="myTabContent">
                        
                    
            
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <img src="{% static 'logotext.png' %}" alt="logo"/>
                        <h3 class="register-heading">Apply for a membership</h3>
                        <div class="row register-form">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="First Name *" name="first_name" />
                                    {% for error in form.first_name.errors %}
                        <p style="color:#DE6262;">{{ error }}</p>
                            {% endfor %}
                        </p>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Last Name *" name="last_name"  />
                                    {% for error in form.last_name.errors %}
                        <p style="color:#DE6262;">{{ error }}</p>
                            {% endfor %}
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="Your Email *" name="email"  />
                                    {% for error in form.email.errors %}
                        <p style="color:#DE6262;">{{ error }}</p>
                            {% endfor %}
                                </div>
                                
                            </div>
                            <div class="col-md-6">
                                
                                <div class="form-group">
                                    <input type="text" name="username" class="form-control" placeholder="Your Username *" />
                                    {% for error in form.username.errors %}
                        <p style="color:#DE6262;">{{ error }}</p>
                            {% endfor %}
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Password *" name="password1"  />
                                    {% for error in form.password1.errors %}
                        <p style="color:#DE6262;">{{ error }}</p>
                            {% endfor %}
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control"  placeholder="Confirm Password *" name="password2"  />
                                    {% for error in form.password2.errors %}
                        <p style="color:#DE6262;">{{ error }}</p>
                            {% endfor %}
                                </div>
                                <input type="submit" class="btnRegister"  value="Register"/>
                            </div>
                            <div class="copy-text">Created with <i class="fa fa-heart" style="color:red;"></i> by <a href="http://eashwerks.tk" style="color:red;" >EASHWERKS</a></div>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    </div>
  {% endblock %}

myapp/templates/myapp/userbooks.html
{% extends 'myapp/base.html' %}

  {% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}

    <a href="" class="btn btn-danger" >Profile</button>

{% endblock %}

myapp/templates/myapp/userpage.html
{% extends 'myapp/base.html' %}
{% block title %}{{request.user.username}}| Get My Book{% endblock %}
{% block login %}
<li class="nav-item">
    <a class="nav-link" href="/logout/">Logout</a>
</li>  
{% endblock %} 

{% block style %}
<style>
    body{ background: -webkit-linear-gradient(left, #DE6262 , #FFB88C);}
    .container{ color:white; background:rgba(0, 0, 0, .5);}
</style>
{% endblock %}
{% block content %}
{% endblock %}